// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTest() {
  return window['go']['app']['App']['CancelTest']();
}

export function Context() {
  return window['go']['app']['App']['Context']();
}

export function DeleteList(arg1) {
  return window['go']['app']['App']['DeleteList'](arg1);
}

export function ExportProxies(arg1, arg2) {
  return window['go']['app']['App']['ExportProxies'](arg1, arg2);
}

export function GetLists() {
  return window['go']['app']['App']['GetLists']();
}

export function GetProgress() {
  return window['go']['app']['App']['GetProgress']();
}

export function GetResult() {
  return window['go']['app']['App']['GetResult']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function IsDone() {
  return window['go']['app']['App']['IsDone']();
}

export function IsTesting() {
  return window['go']['app']['App']['IsTesting']();
}

export function LoadList(arg1) {
  return window['go']['app']['App']['LoadList'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['app']['App']['OnStartup'](arg1);
}

export function ParseProxies(arg1) {
  return window['go']['app']['App']['ParseProxies'](arg1);
}

export function SaveList(arg1, arg2) {
  return window['go']['app']['App']['SaveList'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function StartTest(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['StartTest'](arg1, arg2, arg3, arg4);
}
