// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {app} from '../models';

export function CancelTest():Promise<void>;

export function Context():Promise<context.Context>;

export function DeleteList(arg1:string):Promise<void>;

export function ExportProxies(arg1:Array<app.Proxy>,arg2:string):Promise<string>;

export function GetLists():Promise<Array<string>>;

export function GetProgress():Promise<app.TestProgress>;

export function GetResult():Promise<app.TestResult>;

export function GetSettings():Promise<app.AppSettings>;

export function IsDone():Promise<boolean>;

export function IsTesting():Promise<boolean>;

export function LoadList(arg1:string):Promise<app.ProxyList>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function ParseProxies(arg1:string):Promise<Array<app.Proxy>>;

export function SaveList(arg1:string,arg2:Array<app.Proxy>):Promise<void>;

export function SaveSettings(arg1:app.AppSettings):Promise<void>;

export function StartTest(arg1:Array<app.Proxy>,arg2:string,arg3:number,arg4:number):Promise<void>;
